#pragma once

#define PIN_RC_CHANNEL_1 34
#define PIN_RC_CHANNEL_2 35
#define PIN_RC_CHANNEL_3 32
#define PIN_RC_CHANNEL_4 39
#define PIN_RC_CHANNEL_5 37
#define PIN_RC_CHANNEL_6 33
#define PIN_RC_CHANNEL_7 25
#define PIN_RC_CHANNEL_8 26
#define PIN_MOTOR_LEFT_A 5
#define PIN_MOTOR_LEFT_B 4
#define PIN_MOTOR_LEFT_PWM 2
#define PIN_MOTOR_RIGHT_A 21
#define PIN_MOTOR_RIGHT_B 19
#define PIN_MOTOR_RIGHT_PWM 18


#define PIN_SERVO_RAMP 4
